# Generated by Django 6.0.5 on 2026-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('realisateur', models.CharField(max_length=100)),
                ('acteurs', models.TextField()),
                ('synopsis', models.TextField()),
                ('date_sortie', models.DateField()),
                ('duree', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
